# Generated by Django 5.2.5 on 2025-08-22 10:47

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('project_context', models.TextField(blank=True, null=True)),
                ('project_objectives', models.TextField(blank=True, null=True)),
                ('project_challenges', models.TextField(blank=True, null=True)),
                ('domains_of_expertise', models.JSONField(blank=True, default=list)),
                ('collaboration_type', models.CharField(blank=True, max_length=100, null=True)),
                ('specific_budget', models.FloatField(blank=True, null=True)),
                ('budget_range', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('geographic_zone', models.CharField(blank=True, max_length=150, null=True)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='opportunity_files/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='form.position')),
            ],
        ),
    ]
