# Generated by Django 5.2.5 on 2025-08-22 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='position',
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='collaboration_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='form.position'),
        ),
    ]
