# Generated by Django 5.2.5 on 2025-09-03 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financing',
            name='investor',
        ),
        migrations.AddField(
            model_name='financing',
            name='investor_name',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
